version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py

    volumes:
      - .:/app
    ports:
      - '5000:5000'
    env_file:
      - .env
    restart: unless-stopped

