version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py

    volumes:
      - .:/app
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
